import Head from "next/head";
import Hero from "../Components/Hero";
import Layout from "../Components/Layout";
import Menu from "../Components/Menu";
import Service from "../Components/Service";
import { client } from "../lib/client";
import css from "../styles/Home.module.css";
export default function Home({ pizzas }) {
  return (
    <Layout>
      <div className={css.container}>
        <Head>
          <title>FUDO</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/Logo.png" />
        </Head>
        <main>
          {/* {body} */}
          <Hero />
          <Service />
          <Menu pizzas={pizzas} />
        </main>
      </div>
    </Layout>
  );
}

export const getServerSideProps = async () => {
  const query = '*[_type == "pizza"]';
  const pizzas = await client.fetch(query);
  return {
    props: {
      pizzas,
    },
  };
};
